
import Provide from '@/Redux/Provider'
import Navbar from '../component/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Provide>
          <Navbar /><br />
          {children}
        </Provide>
      </body>
    </html>
  )
}
